# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_music', models.CharField(max_length=100)),
                ('name_singer', models.CharField(max_length=100)),
                ('name_album', models.CharField(max_length=100, null=True)),
                ('img_music', models.ImageField(blank=True, null=True, upload_to='img_music')),
                ('file_music', models.FileField(null=True, upload_to='')),
                ('sunny', models.PositiveIntegerField(default=1, verbose_name='맑음')),
                ('foggy', models.PositiveIntegerField(default=1, verbose_name='안개')),
                ('rainy', models.PositiveIntegerField(default=1, verbose_name='비')),
                ('cloudy', models.PositiveIntegerField(default=1, verbose_name='흐림')),
                ('snowy', models.PositiveIntegerField(default=1, verbose_name='눈')),
            ],
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.MusicList')),
                ('songs', models.ManyToManyField(related_name='song_list', to='music.Music')),
            ],
        ),
    ]
