# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.DateTimeField(auto_created=True)),
                ('name_area', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
            ],
        ),
    ]
